services:
  nginx-app-1:
    image: nginx:alpine
    container_name: nginx-app-1
    environment:
      APP_ENV: production
      APP_NAME: frontend
    restart: unless-stopped

  nginx-app-2:
    image: nginx:alpine
    container_name: nginx-app-2
    environment:
      APP_ENV: debug
      APP_NAME: api
    restart: unless-stopped

  nginx-app-3:
    image: nginx:alpine
    container_name: nginx-app-3
    environment:
      APP_ENV: production
      APP_NAME: admins
    restart: unless-stopped
